export const LISTING_NEWS_GALLERY_MAX = 5
export const LISTING_NEWS_PREVIEW_MAX_BYTES = 8 * 1024 * 1024
export const LISTING_NEWS_MEDIA_MAX_BYTES = 50 * 1024 * 1024
export const LISTING_NEWS_CAROUSEL_VISIBLE = 3
