-- Expand amenity catalog toward glamping.rf coverage + new categories

UPDATE "amenity_catalog" SET "label_ru" = 'Баня / парная', "label_en" = 'Banya / steam bath' WHERE "slug" = 'sauna';

INSERT INTO "amenity_catalog" ("slug", "icon", "label_ru", "label_en", "category", "sort_order") VALUES
  ('water_body', 'ph:drop-duotone', 'Водоём', 'Water body', 'location', 1),
  ('location_river', 'ph:waves-duotone', 'У реки', 'By the river', 'location', 2),
  ('location_forest', 'ph:tree-duotone', 'В лесу', 'In the forest', 'location', 3),
  ('ski_resort', 'ph:snowflake-duotone', 'Горнолыжный курорт', 'Ski resort', 'location', 4),
  ('steam_sauna', 'ph:thermometer-hot-duotone', 'Сауна', 'Sauna', 'outdoor', 9),
  ('bbq_area', 'ph:fire-simple-duotone', 'Барбекю-зона', 'BBQ area', 'outdoor', 14),
  ('fire_pit_zone', 'ph:flame-duotone', 'Костровая зона', 'Fire pit area', 'outdoor', 16),
  ('pool_mini', 'ph:waves-duotone', 'Мини-бассейн', 'Small pool', 'outdoor', 17),
  ('spa_complex', 'ph:sparkle-duotone', 'SPA-комплекс', 'SPA complex', 'outdoor', 18),
  ('restaurant_on_site', 'ph:fork-knife-duotone', 'Ресторан на территории', 'On-site restaurant', 'outdoor', 19),
  ('farm', 'ph:plant-duotone', 'Ферма', 'Farm', 'outdoor', 20),
  ('dog_kennel', 'ph:dog-duotone', 'Собачий питомник', 'Dog kennel', 'outdoor', 21),
  ('sports_ground', 'ph:basketball-duotone', 'Спортивная площадка', 'Sports court', 'outdoor', 22),
  ('hammocks_swings', 'ph:armchair-duotone', 'Гамаки и качели', 'Hammocks & swings', 'outdoor', 23),
  ('sun_loungers', 'ph:sun-duotone', 'Шезлонги', 'Sun loungers', 'outdoor', 24),
  ('horse_riding', 'ph:horse-duotone', 'Конные прогулки', 'Horse riding', 'activities', 1),
  ('excursions', 'ph:map-trifold-duotone', 'Экскурсии', 'Excursions', 'activities', 2),
  ('yoga', 'ph:person-simple-run-duotone', 'Йога', 'Yoga', 'activities', 3),
  ('board_games', 'ph:dice-five-duotone', 'Настольные игры', 'Board games', 'activities', 4),
  ('fishing', 'ph:fish-duotone', 'Рыбалка', 'Fishing', 'activities', 5),
  ('sup_surf', 'ph:surfboard-duotone', 'SUP-сёрф', 'SUP', 'activities', 6),
  ('tennis', 'ph:tennis-ball-duotone', 'Теннис', 'Tennis', 'activities', 7),
  ('cycling', 'ph:bicycle-duotone', 'Велопрогулки', 'Cycling', 'activities', 8),
  ('badminton', 'ph:shuttlecock-duotone', 'Бадминтон', 'Badminton', 'activities', 9),
  ('kayaks', 'ph:boat-duotone', 'Каяки', 'Kayaks', 'activities', 10),
  ('cinema', 'ph:film-slate-duotone', 'Кинотеатр', 'Cinema', 'activities', 11),
  ('atv', 'ph:jeep-duotone', 'Квадроциклы', 'ATV', 'activities', 12),
  ('skiing', 'ph:mountains-duotone', 'Лыжи', 'Skiing', 'activities', 13),
  ('mobile_internet', 'ph:cell-signal-full-duotone', 'Мобильный интернет', 'Mobile internet', 'comfort', 9),
  ('hair_dryer', 'ph:wind-duotone', 'Фен', 'Hair dryer', 'comfort', 10),
  ('towels', 'ph:towel-duotone', 'Полотенца', 'Towels', 'comfort', 11),
  ('shower_gel', 'ph:drop-half-bottom-duotone', 'Гель для душа', 'Shower gel', 'comfort', 12),
  ('shampoo', 'ph:bottle-duotone', 'Шампунь', 'Shampoo', 'comfort', 13),
  ('bathrobes', 'ph:t-shirt-duotone', 'Халаты', 'Bathrobes', 'comfort', 14),
  ('shared_kitchen', 'ph:cooking-pot-duotone', 'Общая кухня', 'Shared kitchen', 'kitchen', 1),
  ('private_kitchen', 'ph:oven-duotone', 'Собственная кухня', 'Private kitchen', 'kitchen', 2),
  ('microwave', 'ph:microwave-duotone', 'Микроволновка', 'Microwave', 'kitchen', 3),
  ('coffee_machine', 'ph:coffee-duotone', 'Кофемашина', 'Coffee machine', 'kitchen', 4),
  ('kettle', 'ph:tea-bag-duotone', 'Чайник', 'Kettle', 'kitchen', 5),
  ('stove', 'ph:fire-duotone', 'Плита', 'Stove', 'kitchen', 6),
  ('dishes', 'ph:bowl-food-duotone', 'Посуда', 'Dishes', 'kitchen', 7),
  ('coffee_maker', 'ph:coffee-duotone', 'Кофеварка', 'Coffee maker', 'kitchen', 8),
  ('wine_glasses', 'ph:wine-duotone', 'Бокалы', 'Wine glasses', 'kitchen', 9),
  ('corkscrew', 'ph:beer-bottle-duotone', 'Штопор', 'Corkscrew', 'kitchen', 10),
  ('kids_menu', 'ph:bowl-food-duotone', 'Детское меню', 'Kids menu', 'kids', 1),
  ('kids_entertainer', 'ph:confetti-duotone', 'Детский аниматор', 'Kids entertainer', 'kids', 2),
  ('crib_on_request', 'ph:baby-duotone', 'Детская кроватка по запросу', 'Crib on request', 'kids', 3)
ON CONFLICT ("slug") DO NOTHING;
